### ISSUE TITLE
What is the point of passing next to condition function?

### ISSUE THREAD

**Issue by naugtur** [elliotttf/express-conditional-middleware#1]
Condition function is expected to synchronously return truthy or falsy, so why pass next? It'd enable calling next twice.

BTW. I just put this module in a product instead of writing it myself. Good test coverage. Thanks!

**Comment by elliotttf** [comment]
`next` is provided in case you wanted to handle an exception in your condition checker, e.g.

``` javascript
conditional(
  function (req, res, next) {
    try {
      // something risky
    }
    catch (e) {
      next(e);
    }

    return true;
  },
  function (req, res, next) {
    res.status(204).end();
  }
);
```

It could lead to double execution if you called it without an error _and_ returned `true`. Maybe that's something that should be prevented in the middleware? Something like...

``` javascript
if (typeof next === 'function') {
  var originalNext = next;
  next = function (err) {
    if (!err) {
      throw new Error('Called next without an error.');
    }
    originalNext();
  }
}
```

Express will definitely complain if you try to send a response more than once so there would be some trail if you did this, but it probably wouldn't be obvious what's wrong...

**Comment by naugtur** [comment]
Thanks for elaborating. I think it's a job for [once](https://www.npmjs.com/package/once). I could PR that, but not sure when exactly ;)

A colleague at work once introduced a bug that would try to write a response after one was already sent and it did weird things. Preventing that would make this tiny module bulletproof.
