### ISSUE TITLE
Failure middleware is passed silently if falsy

### ISSUE THREAD

**Issue by risseraka** [elliotttf/express-conditional-middleware#18]
Hi there,

I introduced the `fail` middleware into the module and use it quite heavily.
Today I've noticed that not passing any failure middleware or passing a falsy middleware gives the same result: middleware is passed silently.

Example:

``` js
const middlewares = {
  a: (req, res, next) { return next(); },
  b: (req, res, next) { return next(); }
};
conditional(false, middlwares.a, middlewares.c);
```

`middlewares.c` is not valid but there's no error message which is due to the line

``` js
if (fail) {
```

It is too late now for me to drop a pull request I'll check that tomorrow.
First idea is to check `conditional`'s arity when called and err when `success` and `fail` middlewares are invalid.

Cheers.

**Comment by elliotttf** [comment]
This is actually a logic error in the calling code and would prevent desirable behavior in the middleware. The code currently checks to see if the `fail` middleware exists, if it doesn't the `next` middleware is executed, effectively giving you a default failure case. This enables things like this:

``` javascript
app.use(
  conditional(someCondition, require('./conditional-route-behavior')),
  require('./default-route-behavior')
)
```

The `conditional-route-behavior` may or may not eventually execute `next()`, invoking `default-route-behavior`, but if `someCondition` is not met the `default-route-behavior` will always be executed.

Closing this as it works as designed.

**Comment by risseraka** [comment]
:ok_hand:
